algoritmo "Ex01_Soma"
// Função : Soma de dois Algarismos
// Autor :  Abner Santos
// Data : 24/08/2021
// Seção de Declarações de Variaveis
var
  num1,num2,resultado:inteiro
inicio
// Seção de Comandos
Escreva("Digite um número a ser somado: ")
Leia(num1)
Escreva("Digite um número a ser somado: ")
Leia(num2)

resultado <- num1 + num2

Escreval("O resultado da soma de ",num1," +",num2," é: ",resultado,".")
fimalgoritmo
