algoritmo "Ex03_multiplicacao"
// Função : Multiplicação de dois Algarismos
// Autor :  Abner Santos
// Data : 24/08/2021
// Seção de Declarações de Variaveis
var
  num1,num2,resultado:inteiro
inicio
// Seção de Comandos
Escreva("Digite um número: ")
Leia(num1)
Escreva("Digite um número: ")
Leia(num2)

resultado <- num1 * num2

Escreval("O resultado da multiplicação de ",num1," x",num2," é: ",resultado,".")
fimalgoritmo
