algoritmo "Ex04_Divisao"
// Função : Multiplicação de dois Algarismos
// Autor :  Abner Santos
// Data : 24/08/2021
// Seção de Declarações de Variaveis
var
  num1,num2,resultado:real
inicio
// Seção de Comandos
Escreva("Digite um número: ")
Leia(num1)
Escreva("Digite um número: ")
Leia(num2)

resultado <- num1 / num2

Escreval("O resultado da divisão de ",num1," :",num2," é: ",resultado:2:2,".")
fimalgoritmo
