algoritmo "Ex07_calculo-area-retangulo"
// Função : Ler dois algarismos, base e altura, e calcular a area de um retangulo.
// Autor :  Abner Santos
// Data : 24/08/2021
// Seção de Declarações de Variaveis
var
  base,altura,area :real
inicio
// Seção de Comandos
Escreva("Insira a base do seu retangulo(m): ")
Leia(base)
Escreva("Insira a altura do seu retangulo(m): ")
Leia(altura)


area <- altura * base

Escreval("A área do seu retangulo é de: ",area,"m².")
fimalgoritmo
