algoritmo "Ex09_calculo-area-quadrado"
// Função : Ler dois algarismos, base e altura, e calcular a area de um quadrado.
// Autor :  Abner Santos
// Data : 24/08/2021
// Seção de Declarações de Variaveis
var
  base,altura,area :real
inicio
// Seção de Comandos
Escreva("Insira a base do seu quadrado(m): ")
Leia(base)
Escreva("Insira a altura do seu quadrado(m): ")
Leia(altura)


area <- altura * base

Escreval("A área do seu quadrado é de: ",area,"m².")
fimalgoritmo
