Algoritmo "Ex48_repeticao6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mr. Obama 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Abner Santos
// Data atual  : 10/09/2021
Var
// Seção de Declarações das variáveis 
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


para i de 101 ate 110 passo 1 faca
Escreval(i)
fimpara

Fimalgoritmo