Algoritmo "Ex49_repeticao7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mr. Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Abner Santos
// Data atual  : 10/09/2021
Var
// Seção de Declarações das variáveis
i, n :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

Escreva("Defina um valor: ")
leia(n)
para i de 1 ate n passo 1 faca
Escreval(i)
fimpara

Fimalgoritmo