Algoritmo "Ex53_repeticao11"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mr. Obama 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2021
Var
// Seção de Declarações das variáveis 
c :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 repita
 c <- c + 1
 escreval(c)
 ate (c = 10)

Fimalgoritmo