Algoritmo "Ex54_repeticao12"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mr. Obama 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2021
Var
// Seção de Declarações das variáveis 
c :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
c <- 10

repita
escreva(c)
c <- c - 1

ate(c = 0)

Fimalgoritmo